<?php

namespace app\models;


use yii\db\ActiveRecord;
use yii\behaviors\TimestampBehavior;
use yii\db\Expression;

class Order extends ActiveRecord
{
    public static function tableName(): string
    {
        return "order";
    }

    public function behaviors(): array
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'attributes' => [
                    ActiveRecord::EVENT_BEFORE_INSERT => ['created_at', 'update_at'],
                    ActiveRecord::EVENT_BEFORE_UPDATE => ['update_at'],
                ],
                "value" => new Expression("NOW()"),
            ]
        ];
    }

    public function getOrderItem()
    {
        return $this->hasMany(OrderItmes::className(), ['order_id' => 'id']);
    }

    public function rules(): array
    {
        return [
            [['name', 'email', 'phone', 'adress'], 'required'],
            [['qty'], 'integer'],
            [['sum'], 'number'],
        ]; // TODO: Change the autogenerated stub
    }

    public function attributeLabels(): array
    {
        return [
            'name' => 'Имя',
            'email' => 'E-mail',
            'phone' => 'телефон',
            'address' => 'адресс',

        ]; // TODO: Change the autogenerated stub
    }
}